### PR TITLE
Connect feedback to backend

### PR DESCRIPTION
**Pull request by bbaayezi**
added axios as well as the logic to get feedback from the localhost server

### CODE REVIEW

**Review by dinojs — CHANGES_REQUESTED** [review]
You got some conflicts!

**Comment by bbaayezi** [comment]
Do you wish to keep your code first? since you said that you will stay with mock data for now.

**Comment by dinojs** [comment]
> > You got some conflicts!
> 
> Do you wish to keep your code first? since you said that you will stay with mock data for now.

I think you need to merge `master` in your branch, that should do it 😄

**Comment by bbaayezi** [comment]
> > > You got some conflicts!
> > 
> > 
> > Do you wish to keep your code first? since you said that you will stay with mock data for now.
> 
> I think you need to merge `master` in your branch, that should do it 😄

Ye I guess I'll just discard any changes I made, could you add `yarn.lock` file to `.gitignore`? I think you don't need that file here

**Comment by bbaayezi** [comment]
Or I can just simply close this PR, you can stick to local mock data now

**Comment by dinojs** [comment]
> > > > You got some conflicts!
> > > 
> > > 
> > > Do you wish to keep your code first? since you said that you will stay with mock data for now.
> > 
> > 
> > I think you need to merge `master` in your branch, that should do it 😄
> 
> Ye I guess I'll just discard any changes I made, could you add `yarn.lock` file to `.gitignore`? I think you don't need that file here

We don't use `yarn`, so you can just delete it.

**Pull request merged**
