### PR TITLE
Create new feedback page: Skeleton ready

### PR DESCRIPTION
**Pull request by dinojs**
- Added /comments route
- Added text fields to input the author's name and feedback's message
- Added comment list retrieved from data.json using AJAX
- Adding new comments successfully updates the view
- Added basic error handling when text fields are empty
- Added Bootstrap components to style code

### CODE REVIEW

**Comment by lukasotocerny** [comment]
I don't think we should add anything to `build` ourselves. I think it'd be better, if we configure CI pipeline to do automatic builds commits to master and push them the Github. Doing them manually 1) worsens the clarity of PRs, 2) can easily get out of sync. @bbaayezi @dinojs wdyt?

**Comment by dinojs** [comment]
> I don't think we should add anything to `build` directory ourselves. I think it'd be better, if we configure CI pipeline to do automatic builds commits to master and push them the Github. Doing them manually 1) worsens the clarity of PRs, 2) can easily get out of sync. @bbaayezi @dinojs wdyt?

I have now removed the build folder and updated the  `.gitignore`.

**Comment by lukasotocerny** [comment]
Make sure to merge Master into the current branch. I've deleted the deployment files on Master.

**Comment by dinojs** [comment]
> Make sure to merge Master into the current branch. I've deleted the deployment files on Master.

👍

**Review by lukasotocerny — APPROVED** [review]
LGMT 👍 but please wait for @bbaayezi to approve as well

**Review by bbaayezi — APPROVED** [review]
LGTM👍

**Pull request merged**
